name: Telegram Scraper Bot

on:
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes
  workflow_dispatch:  # allowing manual runs 

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon python-dotenv

    - name: Run scraper
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        BANNED_KEYWORDS: ${{ secrets.BANNED_KEYWORDS }}
        TAGS_TO_REMOVE: ${{ secrets.TAGS_TO_REMOVE }}
        FETCH_LIMIT: ${{ secrets.FETCH_LIMIT }}
      run: python telegram_scraper.py

    - name: Commit updated JSON
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add telegram_posts.json
        git commit -m "Update posts JSON [skip ci]" || echo "No changes to commit"
        git push
